### ISSUE TITLE
NPE when optional propertiesFile param not specified

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.messaging#107]
The propertiesFile param is optional, but when it's omitted, an NPE results.
A small tweak is needed in KafkaBaseOper.getPropertiesFile() to first check for a null value.

e.g., in the following sample the contents of consumer.properties were instead specified
via the kafkaProperty param.  

```
		stream<rstring key, rstring message> KafkaStream2 = KafkaConsumer()
		{
			param
//				propertiesFile : "etc/consumer.properties" ;
				kafkaProperty : "zookeeper.connect=localhost:2181",
								"group.id=mygroup",
								"zookeeper.session.timeout.ms=400",
								"zookeeper.sync.time.ms=200",
								"auto.commit.interval.ms=1000"
								;
				topic : "mytopic" ;
		}
```
results in:
<---------- Start PE console ---------->
Exception in thread "Thread-11" java.lang.NullPointerException
	at java.io.File.<init>(File.java:289)
	at com.ibm.streamsx.messaging.kafka.KafkaBaseOper.getPropertiesFile(KafkaBaseOper.java:98)
	at com.ibm.streamsx.messaging.kafka.KafkaBaseOper.initialize(KafkaBaseOper.java:46)
	at com.ibm.streamsx.messaging.kafka.KafkaSource.initialize(KafkaSource.java:49)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:713)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:275)

**Comment by Alex-Cook4** [comment]
I ran into this as well. It will be fixed when I deliver Kafka changes that I'm making. That could be as late as the end of July though. I will try to keep my Stream up-to-date though.

**Comment by Alex-Cook4** [comment]
This was fixed by https://github.com/IBMStreams/streamsx.messaging/pull/115. This topic can be closed.
