### ISSUE TITLE
Null pointer exception in Kafka 0.9 Alpha release

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#171]
When no security protocol is specified, this results in a null pointer exception: 

<pre>
Exception in thread "Thread-11" java.lang.NullPointerException
	at com.ibm.streamsx.messaging.kafka.KafkaBaseOper.transformTrustStoreProperty(KafkaBaseOper.java:70)
	at com.ibm.streamsx.messaging.kafka.KafkaBaseOper.initialize(KafkaBaseOper.java:51)
	at com.ibm.streamsx.messaging.kafka.KafkaSink.initialize(KafkaSink.java:69)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:713)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:275)
</pre>
The workaround if you are using a release with this problem is to specify the property in your producer.properties and consumer.properties: 
security.protocol=PLAINTEXT

**Comment by Alex-Cook4** [comment]
New release delivered fixes this.
