### ISSUE TITLE
Kafka SimpleConsumer requires key output attribute

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#177]
Workaround is to have a dummy key attribute in your output Stream. 
<pre>
Exception in thread "Thread-13" java.io.IOException: Unable to find a new Kafka lead Broker after 3 attempts. Unable to proceed.
	at com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.findNewLeader(SimpleConsumerClient.java:166)
	at com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.initialize(SimpleConsumerClient.java:287)... 
</pre>

**Comment by Alex-Cook4** [comment]
This is fixed in the master branch.
