### ISSUE TITLE
KafkaConsumers fail in parallel with InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#309]
There is a problem with the KafkaConsumer API when a client.id is not provided, that multiple consumers starting in parallel will be given a "generated" client.id that should be unique, but ends up being exactly the same of each consumer. I have pasted the exception below and I have reopened an old [JIRA issue](https://issues.apache.org/jira/browse/KAFKA-3992). I'm marking this as a bug, but it's really a bug in the Kafka client, so maybe it's better as a question. 

The workaround is to generate our own client.id: 
```
@parallel(width = 3)
stream<rstring key, rstring message> KafkaStream = KafkaConsumer()
{
	param
		propertiesFile : "etc/consumer.properties";
		topic : $topic;
		kafkaProperty : "client.id=consumer-" + (rstring) getChannel(); 
}
```

The exception typically looks like this: 

```
24 Mar 2017 12:26:57.083 [1151] ERROR #splapptrc,J[0],P[0],KafkaStream[0] M[?:com.ibm.streamsx.messaging.kafka.KafkaSource.produceTuples:-1]  - Error unregistering mbean
org.apache.kafka.common.KafkaException: Error unregistering mbean
	at org.apache.kafka.common.metrics.JmxReporter.unregister(JmxReporter.java:150)
	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:155)
	at org.apache.kafka.common.metrics.JmxReporter.metricChange(JmxReporter.java:77)
	at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:383)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:177)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:162)
	at org.apache.kafka.common.network.Selector$SelectorMetrics.maybeRegisterConnectionMetrics(Selector.java:668)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:302)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:260)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:201)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:998)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:937)
	at com.ibm.streamsx.messaging.kafka.KafkaConsumerClient.getRecords(KafkaConsumerClient.java:94)
	at com.ibm.streamsx.messaging.kafka.KafkaSource.produceTuples(KafkaSource.java:195)
	at com.ibm.streamsx.messaging.kafka.KafkaSource$1.run(KafkaSource.java:161)
	at java.lang.Thread.run(Thread.java:785)
	at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
Caused by: javax.management.InstanceNotFoundException: kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=node-0
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1107)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:439)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:427)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:558)
	at org.apache.kafka.common.metrics.JmxReporter.unregister(JmxReporter.java:148)
	... 19 more

```

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
