### ISSUE TITLE
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=node--4

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.messaging#333]
I am trying using the kafka toolkit which built by ant kafka-0.9.
scenario: to connect to 0.10 broker. but failed. below is the error message.
 whats the reason ?
 is there any possibility to resolve this problem?

M[?:com.ibm.streamsx.messaging.kafka.KafkaSource.produceTuples:-1]  - Error registering mbean kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=node--4
org.apache.kafka.common.KafkaException: Error registering mbean kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=node--4
	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:159)
	at org.apache.kafka.common.metrics.JmxReporter.metricChange(JmxReporter.java:77)
	at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:288)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:177)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:162)
	at org.apache.kafka.common.network.Selector$SelectorMetrics.maybeRegisterConnectionMetrics(Selector.java:641)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:268)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:256)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:211)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:191)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:181)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:888)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:855)
	at com.ibm.streamsx.messaging.kafka.KafkaConsumerClient.getRecords(KafkaConsumerClient.java:94)
	at com.ibm.streamsx.messaging.kafka.KafkaSource.produceTuples(KafkaSource.java:282)
	at com.ibm.streamsx.messaging.kafka.KafkaSource$1.run(KafkaSource.java:248)
	at java.lang.Thread.run(Thread.java:748)
	at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
Caused by: javax.management.InstanceAlreadyExistsException: kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id=node--4
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:157)
	... 19 more

**Comment by schulz2** [comment]
Hi Richard,

from the error message it seems you are trying to start a second client (consumer) with the IDs of an already existing client. Have you tried different "client-id" values?

Kind regards
Norbert

**Comment by sunruns** [comment]
yes,this problem is resolved.
I have another question. how can I get the logs produced by kafkaproducer and kafkaconsumer?
I have set instanceTrace.defaultLevel=trace, but I can't find any information produced by the two operators in the pec.out files.

**Comment by schulz2** [comment]
As the original problem is resolved and the new problem has its own issue, I close this issue here.
